library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)
data<-read.spss(file='data/Koweps_hpc10_2015_beta1.sav',to.data.frame = T)
data<-rename(data, gender=h10_g3, birth=h10_g4, marriage=h10_g10, religion=h10_g11, code_job=h10_eco9, income=p1002_8aq1, code_region=h10_reg7)
mode(data$gender)
table(data$gender)
data$gender<-ifelse(data$gender!=1 & data$gender!=2,NA,data$gender)
table(data$gender)
table(is.na(data$gender))  
data$gender2<-ifelse(data$gender==1,'남자','여자')
barplot(table(data$gender2))
mode(data$income)
summary(data$income)
data$income<-ifelse(data$income>=1 & data$income<=9998,data$income,NA)
summary(data$income)
gender_income<-data %>% filter(!is.na(income))
hist(gender_income$income)
boxplot(gender_income$income)
gender_income2<-gender_income%>%group_by(gender2) %>% summarise(avgincome=mean(income))
ggplot(data=gender_income2,aes(x=gender2,y=avgincome))+geom_col()
mode(data$birth)
summary(data$birth)
table(is.na(data$birth))
data$age<-2015-data$birth+1
summary(data$age)
hist(data$age)
age_income=data%>%filter(!is.na(income)) %>% group_by(age) %>% summarise(avgincome=mean(income))
ggplot(data=age_income,aes(x=age,y=avgincome))+geom_line()
data<-data %>% mutate(ageg=ifelse(age<30,'초년', ifelse(age<60,'중년','노년')))
mode(data$ageg)
table(data$ageg)
barplot(table(data$ageg))
ageg_income<-data %>% filter(!is.na(income)) %>% group_by(ageg) %>% summarise(avgincome=mean(income))
ggplot(data=ageg_income,aes(x=ageg,y=avgincome))+geom_col()+scale_x_discrete(limits=c('초년','중년','노년'))
ageg_gender_income<-data %>% filter(!is.na(income)) %>% group_by(ageg,gender2) %>% summarise(avgincome=mean(income))
ggplot(data=ageg_gender_income,aes(x=ageg,y=avgincome,fill=gender2))+geom_col()+scale_x_discrete(limits=c('초년','중년','노년'))
ggplot(data=ageg_gender_income,aes(x=ageg,y=avgincome,fill=gender2))+geom_col(position="dodge")+scale_x_discrete(limits=c('초년','중년','노년'))
age_gender_income<-data %>% filter(!is.na(income)) %>% group_by(age,gender2) %>% summarise(avgincome=mean(income))
head(age_gender_income)
ggplot(data=age_gender_income,aes(x=age,y=avgincome,col=gender2))+geom_line()
mode(data$code_job)
table(data$code_job)
joblist<-read_excel('data/Koweps_Codebook.xlsx',sheet=2)
head(joblist)
data<-left_join(data,joblist,id="code_job")
data %>% filter(!is.na(income)) %>% select(code_job,job) %>% head()
job_income<- data %>% filter(!is.na(income)) %>% group_by(job) %>% summarise(avgincome=mean(income))
# 과제 )급여를 많이 받는 직종 10개를 추출하여 막대그래프로 그려서 제출
top10 <-job_income %>% arrange(desc(avgincome)) %>% head(10)
ggplot(data=top10, aes(x=job, y=avgincome)) + geom_col()
# 가로막대 회전
ggplot(data=top10, aes(x=job, y=avgincome)) + geom_col() + coord_flip()